apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: latest
  template:
    metadata:
      labels:
        app: latest
    spec:
      containers:
        - name: frontend-container
          image: 513111466874.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:latest  #  app image
          ports:
            - containerPort: 8080 
