name: Terraform Workflow

on:
  push:
    branches:
      - infra  # Trigger on push to the 'main' branch, change if you use a different branch
  pull_request:
    branches:
      - infra  # Trigger on pull request to the 'main' branch
  workflow_dispatch: # Manual trigger from GitHub UI

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out your code from the repository
    
    - name: Set up AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1  # Sets up Terraform on the runner

    - name: Cache Terraform providers
      uses: actions/cache@v2
      with:
        path: ~/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Terraform Init
      run: terraform init  # Initializes Terraform in the current directory
      
    - name: Terraform Validate
      run: terraform validate  # Validates the Terraform configuration

    - name: Terraform Plan
      run: terraform plan  # Runs `terraform plan` to see what changes will be made

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Injects AWS Access Key
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Runs `terraform apply` to apply the changes
      # env:
      #   TF_VAR_my_variable: ${{ secrets.MY_SECRET_VAR }}  # Example of using secret variables (optional)
    #  - name: Terraform Destroy
    #   # if: ${{ github.event_name == 'workflow_dispatch' }}  # This ensures the destroy runs only when triggered manually
    #   run: terraform destroy -auto-approve
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }
